package com.nisaefendioglu.eterationstore.utils

object Constants {
     val brandList = listOf(
        "Lamborghini",
        "Smart",
        "Ferrari",
        "Volkswagen",
        "Mercedes Benz",
        "Tesla",
        "Fiat",
        "Bugatti",
        "Nissan",
        "Aston Martin",
        "Rolls Royce",
        "Chevrolet",
        "Land Rover",
        "Mini",
        "Cadillac",
        "Audi",
        "Kia",
        "Honda",
        "Mazda",
        "Dodge",
        "Polestar",
        "BMW",
        "Ford"
    )
     val modelList = listOf(
        "CTS",
        "Roadster",
        "Taurus",
        "Jetta",
        "Fortwo",
        "A4",
        "Model S",
        "El Camino",
        "Expedition",
        "Focus",
        "Mercielago",
        "Colorado",
        "911",
        "Altima",
        "Accord",
        "Alpine",
        "Wrangler",
        "Grand Caravan",
        "2",
        "XTS",
        "Fiesta",
        "V90",
        "Charger",
        "Camaro",
        "Mustang",
        "Explorer",
        "Beetle",
        "Grand Cherokee",
        "Model Y",
        "Corvette",
        "Land Cruiser",
        "Spyder",
        "Golf",
        "Malibu",
        "LeBaron",
        "Model T",
        "Silverado",
        "PT Cruiser",
        "Challenger",
        "Durango",
        "Element",
        "Volt"
    )
}